{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "from sklearn.datasets import make_regression\n",
    "from sklearn.model_selection import train_test_split\n",
    "from sklearn.decomposition import PCA\n",
    "import numpy as np\n",
    "\n",
    "X, y = make_regression(100000,100,effective_rank=2)\n",
    "X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)\n",
    "\n",
    "pca = PCA(n_components=3)\n",
    "X2D = pca.fit_transform(X_train)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "array([0.24086257, 0.1808738 , 0.09715335])"
      ]
     },
     "execution_count": 2,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "pca.explained_variance_ratio_"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "<matplotlib.lines.Line2D at 0x7fa912ea4550>"
      ]
     },
     "execution_count": 3,
     "metadata": {},
     "output_type": "execute_result"
    },
    {
     "data": {
      "image/png": "iVBORw0KGgoAAAANSUhEUgAAAXQAAAD8CAYAAABn919SAAAAOXRFWHRTb2Z0d2FyZQBNYXRwbG90bGliIHZlcnNpb24zLjMuMiwgaHR0cHM6Ly9tYXRwbG90bGliLm9yZy8vihELAAAACXBIWXMAAAsTAAALEwEAmpwYAAAZ4UlEQVR4nO3de3SU933n8fdXowtIAsRF3CRsBMZcbIMvsg1xkjqNY4PtliSuG5zETrxxiTdxYu9Jt3FOtu3p6Wk3OUm2abaOCetgJ67XOHW8CU2IiTfb2EmMMRBfwWBLICwhLrqDRpfR5bt/zEAGIaFBjHg0z3xe58yZeZ7nNzPfnyQ+58dvnuc35u6IiEjmywm6ABERSQ8FuohISCjQRURCQoEuIhISCnQRkZBQoIuIhMSwgW5mG8zsqJm9OcRxM7PvmFmVmb1uZlemv0wRERlOKiP0x4CVZzi+CliQuK0FHj73skRE5GwNG+ju/gLQfIYmq4EfetxLQImZzUpXgSIikprcNLxGGVCbtF2X2HdoYEMzW0t8FE9RUdFVixYtSsPby3D2NUQBmFdaFHAl51+/O/39iXt3+j3+2BOPT7vn1H3x7eTHJ44B/OE5ODgeb5u8zYm28ecmDkmWKy0uYOakcSN67s6dOxvdvXSwY+kIdBtk36B/s+6+HlgPUFlZ6Tt27EjD28twPva9rQA89dkVAVeSOnenvbuXlmgPrZ0xWjt6aO3s4VhnD8e6emjr7OF4Vy/Hu3pp7+qhvbuX9u4+2rt76OjuIxrrpaun/6ze0xK3HIP83BzyIznk50YoyM0hL2Lk5+aQF8khN5JDfsTIzckhN2LkR3KI5FjiWHx/JAdyIznk5hg5ZuRFjJwcI2IW35d4nJNjRJIfG0QSx3PMyDES90ZODhgnjsUfR3LAzBJ1/6GN2an7zRL9G/Jx/CdwyrHE/hOvd/LnlNh38rGd+Pkl7Utqe+pPmEHa2CAtTn2uDRozA19/cGdqYym8QApvcdbvXVSQy8RxeSN8TTsw1LF0BHodMCdpuxyoT8PrSggd7+rhyLFujhzr4ujxLo4e66bheDcN7d00tcdobO+mORqjpSNGT9/QY9n8SA4Tx+dSXJBL8bj4fVnJeIoLiikqyKWoIJfC/AhF+bmMy49QmBehMD/CuLwIBXk5jM+LP47fchiXG9+fnwhskUyUjkDfBNxnZhuBa4E2dz9tukWyw7GuHg40dvBucwe1LR3UNndwsLWTQ61d1Ld2cry797TnjM+LUDqhgKnF+ZRPLmRZeQlTivOZUphPSWEekxP3k8bHbxPH5zEuLxJA70TGtmED3cyeBK4HpplZHfC3QB6Au68DNgM3A1VAB3D3aBUrY0N/v3OwtZO9h49T3dCeuEXZ3xilORo7pW1JYR5lJeO5YGohK+ZPZeakccycOI4ZE8cxY2IB0yeOoyg/ktJ/fUXkzIYNdHe/Y5jjDnw+bRXJmBLr7WfP4WO8efAYu+rb2H3oGG8fPk401neyTemEAuZNK+KmS2Yyd2ohc6cVccGUQsonj2fCCOcJReTspWPKRULkUFsnO2pa2HmghVdrW9ldf4xYX/zDxQnjclk8ayK3V87h4hkTWDizmIumT2DSeIW2yFigQM9yh9o62VrdxIvVTWytbuJgaycQn9deWj6Ju6+by9LyEi4rm8ScKeM1NSIyhinQs0yst5/tNc38eu9Rfr23gXeOtgMwuTCP5fOm8pn3VnD13CksnjVBZ3uIZBgFehbod6e1o4cHNr7Cr/Yc5XhXL/mRHK6pmMKfV87huoumsWjmBHJyNPoWyWQK9JCK9fbzm3ca2PRaPTsPtNDv0NjezcpLZnLjJTN5z/ypFBXo1y8SJvoXHTJVR4/z1PZanvn9QZqiMUoK85hWHD/H+9/ve6+mUURCTIEeAj19/WzZdZgfvFjD9poWcnOMGxbP4M+uKuf9F5dy5/e3ASjMRUJOgZ7B2jp7+NeXDvD41gMcPtbFBVMK+erNi/nIlWVMKy4IujwROc8U6Bno6PEuNvy2hideOsDx7l7et2Aa//jRS7n+4un6YFMkiynQM0hLNMa6F6r5wYs1xHr7ufmyWdz7R/O5tGxS0KWJyBigQM8AnbE+HvnNPta/sI/2WC+rl83m/hsupmJa9q1vLiJDU6CPYe7Optfq+fov9lDf1sWNS2bwpRsXsnDmhKBLE5ExSIE+Rr195Dhf/T9vsL2mhUtmT+SfPnY5186bGnRZIjKGKdDHmK6ePr77H1U8/Hw1RQW5fO2jl3F75Rwi+rBTRIahQB9D3qhr44GnXqG6IcqHL5/Nf7t1iU4/FJGUKdDHgL5+Z93z1fzTc28zrbiAx+6+musXTg+6LBHJMAr0gB051sUXnnyFl/c3c8tls/iHj1xKSWF+0GWJSAZSoAfoxepGvvjkK3TE+vjW7cv46JVlWm9cREZMgR4Ad+fh56v55pa9VEwrYuPa5Vw0Xaciisi5UaCfZ929fXz56df5yav13Lp0Fl+7bSnFWsZWRNJASXIeNUdjfPbxHWyvaeG/3rSQz10/X1MsIpI2CvTz5N2mDu7asI36ti7+5x1X8CfLZgddkoiEjAL9PKg6epxPPLKN7t5+nvyL5Vx14eSgSxKREFKgj7I3D7Zx14aXieQYT61doXVYRGTUKNBH0Wu1rXzy+9uYOC6PJ+65lrlaHVFERpECfZS8degYd214mZLCPDauXUFZyfigSxKRkNOXTI6C6oZ27vz+NsbnRfjf9yxXmIvIeaFAT7O6lg4+8b/iX8r8xF9cy5wphQFXJCLZQlMuadTW2cOnH91ONNbLU2tXML+0OOiSRCSLaISeJrHefu59fCcHmqJ8786rWDJ7YtAliUiW0Qg9DdydrzzzBlv3NfGt25fxnvnTgi5JRLKQRuhp8PDz1fz493U8cMMCbruqPOhyRCRLKdDP0e+qGvnmlr3cunQW939wQdDliEgWU6Cfg/rWTr7w5CvMLy3m67ct1UJbIhIoBfoIdff28bknfk93Tx8Pf/IqirQErogELKVAN7OVZrbXzKrM7MFBjk8ys383s9fMbJeZ3Z3+UseWr/1iD6/WtvKN25dx0XSdnigiwRs20M0sAjwErAKWAHeY2ZIBzT4P7Hb3ZcD1wLfMLLRfjPn82w08+rsaPrXiQm6+bFbQ5YiIAKmN0K8Bqtx9n7vHgI3A6gFtHJhg8UnkYqAZ6E1rpWNEU3s3f/lvr3HxjGK+cvPioMsRETkplUAvA2qTtusS+5L9C7AYqAfeAO539/6BL2Rma81sh5ntaGhoGGHJwXF3HnzmDdo6evjnNVcwLi8SdEkiIielEuiDnbrhA7ZvAl4FZgOXA/9iZqddKunu69290t0rS0tLz7LU4D21vZbndh/hr1YuZPEsXQkqImNLKoFeB8xJ2i4nPhJPdjfwjMdVAfuBRekpcWw43NbFP/z8LVbMm8p/uq4i6HJERE6TSqBvBxaYWUXig841wKYBbd4FPghgZjOAhcC+dBYaJHfnr3/6JrG+fr5222Xk5Oh8cxEZe4Y9edrde83sPmALEAE2uPsuM7s3cXwd8PfAY2b2BvEpmi+7e+Mo1n1ePfvmYZ7bfYQHVy3iwqn61iERGZtSuhrG3TcDmwfsW5f0uB64Mb2ljQ1tnT38zaZdXDJ7Ive8V1MtIjJ26fLGYXz92T00R2M8+umryY3owloRGbuUUGewq76NJ19+l7tWXMilZZOCLkdE5IwU6ENwd/5u024mF+bzwA0XB12OiMiwFOhD+Pkbh3i5ppm/vHEhk8bnBV2OiMiwFOiD6Iz18d8372HxrIl87Oo5wz9BRGQMUKAPYv0L+zjY2snf/skSIjrnXEQyhAJ9gMb2br73QjWrLp3J8nlTgy5HRCRlCvQBHv51NV09fXzpxoVBlyIiclYU6EkOtXXy+EsHuO3Kcn1phYhkHAV6ku/8qgp354v6smcRyUAK9ISaxig/2lHLx6+5gDlTCoMuR0TkrCnQE779f98mL2J8/o8vCroUEZERUaATH51veq2eT62Yy/QJ44IuR0RkRBTowPdeqCY3ksNn3qfVFEUkc2V9oB9u6+LpnXX8eWW5RuciktGyPtAf+c0++h0++/75QZciInJOsjrQW6Ixntj2Ln+6bLbObBGRjJfVgf7oizV09vTxn6/X6FxEMl/WBnpnrI8fbq3hQ0tmcPGMCUGXIyJyzrI20H/66kFaO3r0PaEiEhpZGejuzmMv1rBo5gSuqZgSdDkiImmRlYG+bX8zew4f5+7r5mKm9c5FJByyMtAf+10NJYV5rL68LOhSRETSJusC/WBrJ7/cfZg1V1/AuLxI0OWIiKRN1gX641sPAHDnigsDrkREJL2yKtC7evrYuP1dblwyk7KS8UGXIyKSVlkV6L/cfYTWjh4+sfyCoEsREUm7rAr0H22vpaxkPNfNnxZ0KSIiaZc1gV7b3MFvqxq5vbKcnBydqigi4ZM1gf5vO+swg9sr5wRdiojIqMiKQO/rd57eUct7L5qmD0NFJLSyItB/W9VIfVsXH7tao3MRCa+sCPQfba9lcmEeH1oyI+hSRERGTegDva2jh+d2H+HDV5RRkKsrQ0UkvFIKdDNbaWZ7zazKzB4cos31Zvaqme0ys+fTW+bIbdl9mFhfPx+5Quu2iEi45Q7XwMwiwEPAh4A6YLuZbXL33UltSoDvAivd/V0zmz5K9Z61n79+iDlTxnNZ2aSgSxERGVWpjNCvAarcfZ+7x4CNwOoBbT4OPOPu7wK4+9H0ljkyLdEYv6tq5JbLZmuZXBEJvVQCvQyoTdquS+xLdjEw2cx+bWY7zeyuwV7IzNaa2Q4z29HQ0DCyis/CL3cfprffuXXprFF/LxGRoKUS6IMNbX3Adi5wFXALcBPw12Z28WlPcl/v7pXuXllaWnrWxZ6tn71+iAunFnLJ7Imj/l4iIkFLJdDrgOQTuMuB+kHaPOvuUXdvBF4AlqWnxJFpau/mxeombl06S9MtIpIVUgn07cACM6sws3xgDbBpQJufAu8zs1wzKwSuBd5Kb6lnZ8uuI/T1O7dcNjvIMkREzpthz3Jx914zuw/YAkSADe6+y8zuTRxf5+5vmdmzwOtAP/CIu785moUP5+dv1DNvWhGLZ00IsgwRkfNm2EAHcPfNwOYB+9YN2P4G8I30lTZyzdEYW6ub+Nz1F2m6RUSyRiivFN22r4l+hw8sGjOnw4uIjLpQBvrWfU0U5kdYWq6LiUQke4Qy0F/a10Tl3CnkRULZPRGRQYUu8Rrbu3n7SDvL500JuhQRkfMqdIG+bV8zAMvnTQ24EhGR8yt0gf7SviaK8iNajEtEsk4oA13z5yKSjUKVeg3Hu3nnaLumW0QkK4Uq0LftbwJgxXwFuohkn1AF+on580u1uqKIZKFQBfrW6iaurphCrubPRSQLhSb5jh7vorohygrNn4tIlgpNoO85dByApeUlwRYiIhKQ0AR6TVMUgHmlRQFXIiISjNAE+v7GKIX5EaZPKAi6FBGRQIQm0Gsao1w4tUjrn4tI1gpNoO9vjFIxrTDoMkREAhOKQO/p66e2pZOKaZo/F5HsFYpAr2vppK/fmTtVgS4i2SsUgV7TGD/DRSN0EclmoQj0fQp0EZFwBHpNY5QJ43KZUpQfdCkiIoEJR6A3RamYplMWRSS7hSLQ9zdG9YGoiGS9jA/0rp4+DrbqlEURkYwP9NrmDtz1gaiISMYH+v7EGS5zFegikuUyPtBPrLJYoTl0EclyGR/o+xujTCnKZ1JhXtCliIgEKhSBPneqFuUSEcn4QK9p7ND8uYgIGR7oHbFeDh/rYp4CXUQkswO9prED0BkuIiKQ4YF++FgnAGUl4wOuREQkeBkd6M3RHgCmFul7REVEUgp0M1tpZnvNrMrMHjxDu6vNrM/M/ix9JQ6tJRoDYHKRTlkUERk20M0sAjwErAKWAHeY2ZIh2n0d2JLuIofS3BEjL2IUF+Ser7cUERmzUhmhXwNUufs+d48BG4HVg7T7AvBj4Gga6zujlmiMyYX5WjZXRITUAr0MqE3arkvsO8nMyoCPAOvO9EJmttbMdpjZjoaGhrOt9TTN0Zi+1EJEJCGVQB9s+OsDtr8NfNnd+870Qu6+3t0r3b2ytLQ0xRKH1tIRH6GLiAikMvlcB8xJ2i4H6ge0qQQ2JqY+pgE3m1mvu/8kHUUOpTkaY9HMiaP5FiIiGSOVQN8OLDCzCuAgsAb4eHIDd6848djMHgN+NtphDtDS0aMzXEREEoYNdHfvNbP7iJ+9EgE2uPsuM7s3cfyM8+ajpa/fae2IMUVTLiIiQGojdNx9M7B5wL5Bg9zdP33uZQ3vWGcP/Q6T9aGoiAiQwVeKNnfELyrSWS4iInEZG+gnrxLVlIuICJDBgd4c1QhdRCRZxgZ6S8eJdVwU6CIikMGBfmKlRZ3lIiISl7GB3tIRY1xeDuPzI0GXIiIyJmRsoDdHdQ66iEiyjA30lmhM8+ciIkkyNtCbO7TSoohIsowN9BNroYuISFzGBrrWQhcROVVGBnpPXz/Huno1QhcRSZKRgd7akTgHXUvnioiclJGBrqtERUROl5GBfnIdF025iIiclJGBfnKlRY3QRUROyshA11roIiKny8hAPzFCLynUh6IiIidkZKA3R3soLsilIFcLc4mInJCRgd7SEWOyTlkUETlFRga6VloUETldRgZ6fISuQBcRSZaRga4RuojI6TIy0LUWuojI6TIu0Lt6+ojG+nQOuojIABkX6CcW5tJKiyIip8q4QD+5jotOWxQROUXGBfrJlRY1QhcROUXGBfofRugKdBGRZBkX6B9YNJ3NX3wfF0wtDLoUEZExJTfoAs5WcUEuS2ZPDLoMEZExJ+NG6CIiMjgFuohISCjQRURCIqVAN7OVZrbXzKrM7MFBjn/CzF5P3F40s2XpL1VERM5k2EA3swjwELAKWALcYWZLBjTbD/yRuy8F/h5Yn+5CRUTkzFIZoV8DVLn7PnePARuB1ckN3P1Fd29JbL4ElKe3TBERGU4qgV4G1CZt1yX2DeUzwC8GO2Bma81sh5ntaGhoSL1KEREZViqBboPs80Ebmn2AeKB/ebDj7r7e3SvdvbK0tDT1KkVEZFipXFhUB8xJ2i4H6gc2MrOlwCPAKndvSk95IiKSqlRG6NuBBWZWYWb5wBpgU3IDM7sAeAa4093fTn+ZIiIynGFH6O7ea2b3AVuACLDB3XeZ2b2J4+uAvwGmAt81M4Bed68cvbJFRGSglNZycffNwOYB+9YlPb4HuCe9pYmIyNnQlaIiIiGhQBcRCQkFuohISCjQRURCQoEuIhISCnQRkZBQoIuIhIQCXUQkJBToIiIhoUAXEQkJBbqISEgo0EVEQkKBLiISEgp0EZGQUKCLiISEAl1EJCQU6CIiIaFAFxEJCQW6iEhIKNBFREJCgS4iEhIKdBGRkFCgi4iEhAJdRCQkFOgiIiGhQBcRCQkFuohISCjQRURCQoEuIhISCnQRkZBQoIuIhIQCXUQkJBToIiIhoUAXEQkJBbqISEikFOhmttLM9ppZlZk9OMhxM7PvJI6/bmZXpr9UERE5k2ED3cwiwEPAKmAJcIeZLRnQbBWwIHFbCzyc5jpFRGQYqYzQrwGq3H2fu8eAjcDqAW1WAz/0uJeAEjObleZaRUTkDHJTaFMG1CZt1wHXptCmDDiU3MjM1hIfwQO0m9nes6h1GtB4Fu3DIm39/tG96XiV80K/6+yRjX2Gc+v3hUMdSCXQbZB9PoI2uPt6YH0K73l6EWY73L1yJM/NZNnY72zsM2Rnv7OxzzB6/U5lyqUOmJO0XQ7Uj6CNiIiMolQCfTuwwMwqzCwfWANsGtBmE3BX4myX5UCbux8a+EIiIjJ6hp1ycfdeM7sP2AJEgA3uvsvM7k0cXwdsBm4GqoAO4O5RqHVEUzUhkI39zsY+Q3b2Oxv7DKPUb3M/bapbREQykK4UFREJCQW6iEhIZESgD7f0QBiY2Rwz+w8ze8vMdpnZ/Yn9U8zsOTN7J3E/Oeha083MImb2ipn9LLGdDX0uMbOnzWxP4ne+Ikv6/V8Sf99vmtmTZjYubP02sw1mdtTM3kzaN2QfzewriWzba2Y3nct7j/lAT3HpgTDoBb7k7ouB5cDnE/18EPiVuy8AfpXYDpv7gbeStrOhz/8MPOvui4BlxPsf6n6bWRnwRaDS3S8lfpLFGsLX78eAlQP2DdrHxL/xNcAlied8N5F5IzLmA53Ulh7IeO5+yN1/n3h8nPg/8DLiff1BotkPgA8HUuAoMbNy4BbgkaTdYe/zROD9wPcB3D3m7q2EvN8JucB4M8sFColfrxKqfrv7C0DzgN1D9XE1sNHdu919P/EzBa8Z6XtnQqAPtaxAaJnZXOAKYBsw48Q5/Yn76QGWNhq+DfwV0J+0L+x9ngc0AI8mppoeMbMiQt5vdz8IfBN4l/iyIG3u/ktC3u+EofqY1nzLhEBPaVmBsDCzYuDHwAPufizoekaTmd0KHHX3nUHXcp7lAlcCD7v7FUCUzJ9mGFZi3ng1UAHMBorM7JPBVhW4tOZbJgR61iwrYGZ5xMP8CXd/JrH7yImVKxP3R4OqbxRcB/ypmdUQn0r7YzP7V8LdZ4j/Tde5+7bE9tPEAz7s/b4B2O/uDe7eAzwDvIfw9xuG7mNa8y0TAj2VpQcynpkZ8TnVt9z9fyQd2gR8KvH4U8BPz3dto8Xdv+Lu5e4+l/jv9f+5+ycJcZ8B3P0wUGtmCxO7PgjsJuT9Jj7VstzMChN/7x8k/llR2PsNQ/dxE7DGzArMrIL4d0q8POJ3cfcxfyO+rMDbQDXw1aDrGaU+vpf4f7VeB15N3G4GphL/VPydxP2UoGsdpf5fD/ws8Tj0fQYuB3Ykft8/ASZnSb//DtgDvAk8DhSErd/Ak8Q/I+ghPgL/zJn6CHw1kW17gVXn8t669F9EJCQyYcpFRERSoEAXEQkJBbqISEgo0EVEQkKBLiISEgp0EZGQUKCLiITE/wenpq2zx3KkNAAAAABJRU5ErkJggg==\n",
      "text/plain": [
       "<Figure size 432x288 with 1 Axes>"
      ]
     },
     "metadata": {
      "needs_background": "light"
     },
     "output_type": "display_data"
    }
   ],
   "source": [
    "# find dimension that give 95% of variance\n",
    "import matplotlib.pyplot as plt\n",
    "pca = PCA()\n",
    "pca.fit(X_train)\n",
    "cumsum = np.cumsum(pca.explained_variance_ratio_)\n",
    "d = np.argmax(cumsum >= 0.95) +1\n",
    "plt.plot(np.arange(len(cumsum))+1, cumsum)\n",
    "plt.ylim(0,1)\n",
    "plt.axvline(x=d)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "(80000, 26)\n"
     ]
    }
   ],
   "source": [
    "# same thing, but way less work\n",
    "pca = PCA(n_components=0.95)\n",
    "x_reduced = pca.fit_transform(X_train)\n",
    "print(x_reduced.shape)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "0.9532010386454087\n"
     ]
    }
   ],
   "source": [
    "# run way faster O(m x d^2) + O(d^3) rather than O(m x n^2) + O(n^3)\n",
    "# with d as the reduced dimension, m as the instances, and n as inputs\n",
    "rnd_pca = PCA(n_components=26, svd_solver='randomized')\n",
    "X_reduced = rnd_pca.fit_transform(X_train)\n",
    "print(np.sum(pca.explained_variance_ratio_))\n",
    "\n",
    "# for incromental/on the fly use IncrementalPCA"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [],
   "source": [
    "# numpy has a memmap fuctions that allows for arrays \n",
    "# to be stored on disk and loaded when neededd!!!"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {},
   "outputs": [],
   "source": [
    "from sklearn.decomposition import KernelPCA\n",
    "X, y = make_regression(1000,10,effective_rank=2)\n",
    "X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)\n",
    "# using kernels (rbf in this case) to do PCA\n",
    "rbf_pca = KernelPCA(n_components = 2, kernel='rbf', gamma=0.04)\n",
    "x_reduced = rbf_pca.fit_transform(X_train)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/pipeline.py\", line 335, in fit\n",
      "    self._final_estimator.fit(Xt, y, **fit_params_last_step)\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py\", line 1345, in fit\n",
      "    check_classification_targets(y)\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/utils/multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  FitFailedWarning)\n",
      "/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/pipeline.py\", line 335, in fit\n",
      "    self._final_estimator.fit(Xt, y, **fit_params_last_step)\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py\", line 1345, in fit\n",
      "    check_classification_targets(y)\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/utils/multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  FitFailedWarning)\n",
      "/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/pipeline.py\", line 335, in fit\n",
      "    self._final_estimator.fit(Xt, y, **fit_params_last_step)\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py\", line 1345, in fit\n",
      "    check_classification_targets(y)\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/utils/multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  FitFailedWarning)\n",
      "/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/pipeline.py\", line 335, in fit\n",
      "    self._final_estimator.fit(Xt, y, **fit_params_last_step)\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py\", line 1345, in fit\n",
      "    check_classification_targets(y)\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/utils/multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  FitFailedWarning)\n",
      "/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/pipeline.py\", line 335, in fit\n",
      "    self._final_estimator.fit(Xt, y, **fit_params_last_step)\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py\", line 1345, in fit\n",
      "    check_classification_targets(y)\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/utils/multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  FitFailedWarning)\n",
      "/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/pipeline.py\", line 335, in fit\n",
      "    self._final_estimator.fit(Xt, y, **fit_params_last_step)\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py\", line 1345, in fit\n",
      "    check_classification_targets(y)\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/utils/multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  FitFailedWarning)\n",
      "/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/pipeline.py\", line 335, in fit\n",
      "    self._final_estimator.fit(Xt, y, **fit_params_last_step)\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py\", line 1345, in fit\n",
      "    check_classification_targets(y)\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/utils/multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  FitFailedWarning)\n",
      "/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/pipeline.py\", line 335, in fit\n",
      "    self._final_estimator.fit(Xt, y, **fit_params_last_step)\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py\", line 1345, in fit\n",
      "    check_classification_targets(y)\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/utils/multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  FitFailedWarning)\n",
      "/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/pipeline.py\", line 335, in fit\n",
      "    self._final_estimator.fit(Xt, y, **fit_params_last_step)\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py\", line 1345, in fit\n",
      "    check_classification_targets(y)\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/utils/multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  FitFailedWarning)\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/pipeline.py\", line 335, in fit\n",
      "    self._final_estimator.fit(Xt, y, **fit_params_last_step)\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py\", line 1345, in fit\n",
      "    check_classification_targets(y)\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/utils/multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  FitFailedWarning)\n",
      "/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/pipeline.py\", line 335, in fit\n",
      "    self._final_estimator.fit(Xt, y, **fit_params_last_step)\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py\", line 1345, in fit\n",
      "    check_classification_targets(y)\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/utils/multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  FitFailedWarning)\n",
      "/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/pipeline.py\", line 335, in fit\n",
      "    self._final_estimator.fit(Xt, y, **fit_params_last_step)\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py\", line 1345, in fit\n",
      "    check_classification_targets(y)\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/utils/multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  FitFailedWarning)\n",
      "/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/pipeline.py\", line 335, in fit\n",
      "    self._final_estimator.fit(Xt, y, **fit_params_last_step)\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py\", line 1345, in fit\n",
      "    check_classification_targets(y)\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/utils/multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  FitFailedWarning)\n",
      "/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/pipeline.py\", line 335, in fit\n",
      "    self._final_estimator.fit(Xt, y, **fit_params_last_step)\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py\", line 1345, in fit\n",
      "    check_classification_targets(y)\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/utils/multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  FitFailedWarning)\n",
      "/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/pipeline.py\", line 335, in fit\n",
      "    self._final_estimator.fit(Xt, y, **fit_params_last_step)\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py\", line 1345, in fit\n",
      "    check_classification_targets(y)\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/utils/multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  FitFailedWarning)\n",
      "/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/pipeline.py\", line 335, in fit\n",
      "    self._final_estimator.fit(Xt, y, **fit_params_last_step)\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py\", line 1345, in fit\n",
      "    check_classification_targets(y)\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/utils/multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  FitFailedWarning)\n",
      "/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/pipeline.py\", line 335, in fit\n",
      "    self._final_estimator.fit(Xt, y, **fit_params_last_step)\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py\", line 1345, in fit\n",
      "    check_classification_targets(y)\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/utils/multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  FitFailedWarning)\n",
      "/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/pipeline.py\", line 335, in fit\n",
      "    self._final_estimator.fit(Xt, y, **fit_params_last_step)\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py\", line 1345, in fit\n",
      "    check_classification_targets(y)\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/utils/multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  FitFailedWarning)\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/pipeline.py\", line 335, in fit\n",
      "    self._final_estimator.fit(Xt, y, **fit_params_last_step)\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py\", line 1345, in fit\n",
      "    check_classification_targets(y)\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/utils/multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  FitFailedWarning)\n",
      "/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/pipeline.py\", line 335, in fit\n",
      "    self._final_estimator.fit(Xt, y, **fit_params_last_step)\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py\", line 1345, in fit\n",
      "    check_classification_targets(y)\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/utils/multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  FitFailedWarning)\n",
      "/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/pipeline.py\", line 335, in fit\n",
      "    self._final_estimator.fit(Xt, y, **fit_params_last_step)\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py\", line 1345, in fit\n",
      "    check_classification_targets(y)\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/utils/multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  FitFailedWarning)\n",
      "/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/pipeline.py\", line 335, in fit\n",
      "    self._final_estimator.fit(Xt, y, **fit_params_last_step)\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py\", line 1345, in fit\n",
      "    check_classification_targets(y)\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/utils/multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  FitFailedWarning)\n",
      "/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/pipeline.py\", line 335, in fit\n",
      "    self._final_estimator.fit(Xt, y, **fit_params_last_step)\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py\", line 1345, in fit\n",
      "    check_classification_targets(y)\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/utils/multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  FitFailedWarning)\n",
      "/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/pipeline.py\", line 335, in fit\n",
      "    self._final_estimator.fit(Xt, y, **fit_params_last_step)\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py\", line 1345, in fit\n",
      "    check_classification_targets(y)\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/utils/multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  FitFailedWarning)\n",
      "/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/pipeline.py\", line 335, in fit\n",
      "    self._final_estimator.fit(Xt, y, **fit_params_last_step)\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py\", line 1345, in fit\n",
      "    check_classification_targets(y)\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/utils/multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  FitFailedWarning)\n",
      "/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/pipeline.py\", line 335, in fit\n",
      "    self._final_estimator.fit(Xt, y, **fit_params_last_step)\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py\", line 1345, in fit\n",
      "    check_classification_targets(y)\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/utils/multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  FitFailedWarning)\n",
      "/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/pipeline.py\", line 335, in fit\n",
      "    self._final_estimator.fit(Xt, y, **fit_params_last_step)\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py\", line 1345, in fit\n",
      "    check_classification_targets(y)\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/utils/multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  FitFailedWarning)\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/pipeline.py\", line 335, in fit\n",
      "    self._final_estimator.fit(Xt, y, **fit_params_last_step)\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py\", line 1345, in fit\n",
      "    check_classification_targets(y)\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/utils/multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  FitFailedWarning)\n",
      "/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/pipeline.py\", line 335, in fit\n",
      "    self._final_estimator.fit(Xt, y, **fit_params_last_step)\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py\", line 1345, in fit\n",
      "    check_classification_targets(y)\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/utils/multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  FitFailedWarning)\n",
      "/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/pipeline.py\", line 335, in fit\n",
      "    self._final_estimator.fit(Xt, y, **fit_params_last_step)\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py\", line 1345, in fit\n",
      "    check_classification_targets(y)\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/utils/multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  FitFailedWarning)\n",
      "/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/pipeline.py\", line 335, in fit\n",
      "    self._final_estimator.fit(Xt, y, **fit_params_last_step)\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py\", line 1345, in fit\n",
      "    check_classification_targets(y)\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/utils/multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  FitFailedWarning)\n",
      "/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/pipeline.py\", line 335, in fit\n",
      "    self._final_estimator.fit(Xt, y, **fit_params_last_step)\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py\", line 1345, in fit\n",
      "    check_classification_targets(y)\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/utils/multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  FitFailedWarning)\n",
      "/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/pipeline.py\", line 335, in fit\n",
      "    self._final_estimator.fit(Xt, y, **fit_params_last_step)\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py\", line 1345, in fit\n",
      "    check_classification_targets(y)\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/utils/multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  FitFailedWarning)\n",
      "/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/pipeline.py\", line 335, in fit\n",
      "    self._final_estimator.fit(Xt, y, **fit_params_last_step)\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py\", line 1345, in fit\n",
      "    check_classification_targets(y)\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/utils/multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  FitFailedWarning)\n",
      "/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/pipeline.py\", line 335, in fit\n",
      "    self._final_estimator.fit(Xt, y, **fit_params_last_step)\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py\", line 1345, in fit\n",
      "    check_classification_targets(y)\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/utils/multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  FitFailedWarning)\n",
      "/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/pipeline.py\", line 335, in fit\n",
      "    self._final_estimator.fit(Xt, y, **fit_params_last_step)\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py\", line 1345, in fit\n",
      "    check_classification_targets(y)\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/utils/multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  FitFailedWarning)\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/pipeline.py\", line 335, in fit\n",
      "    self._final_estimator.fit(Xt, y, **fit_params_last_step)\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py\", line 1345, in fit\n",
      "    check_classification_targets(y)\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/utils/multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  FitFailedWarning)\n",
      "/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/pipeline.py\", line 335, in fit\n",
      "    self._final_estimator.fit(Xt, y, **fit_params_last_step)\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py\", line 1345, in fit\n",
      "    check_classification_targets(y)\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/utils/multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  FitFailedWarning)\n",
      "/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/pipeline.py\", line 335, in fit\n",
      "    self._final_estimator.fit(Xt, y, **fit_params_last_step)\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py\", line 1345, in fit\n",
      "    check_classification_targets(y)\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/utils/multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  FitFailedWarning)\n",
      "/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/pipeline.py\", line 335, in fit\n",
      "    self._final_estimator.fit(Xt, y, **fit_params_last_step)\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py\", line 1345, in fit\n",
      "    check_classification_targets(y)\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/utils/multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  FitFailedWarning)\n",
      "/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/pipeline.py\", line 335, in fit\n",
      "    self._final_estimator.fit(Xt, y, **fit_params_last_step)\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py\", line 1345, in fit\n",
      "    check_classification_targets(y)\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/utils/multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  FitFailedWarning)\n",
      "/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/pipeline.py\", line 335, in fit\n",
      "    self._final_estimator.fit(Xt, y, **fit_params_last_step)\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py\", line 1345, in fit\n",
      "    check_classification_targets(y)\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/utils/multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  FitFailedWarning)\n",
      "/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/pipeline.py\", line 335, in fit\n",
      "    self._final_estimator.fit(Xt, y, **fit_params_last_step)\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py\", line 1345, in fit\n",
      "    check_classification_targets(y)\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/utils/multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  FitFailedWarning)\n",
      "/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/pipeline.py\", line 335, in fit\n",
      "    self._final_estimator.fit(Xt, y, **fit_params_last_step)\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py\", line 1345, in fit\n",
      "    check_classification_targets(y)\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/utils/multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  FitFailedWarning)\n",
      "/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/pipeline.py\", line 335, in fit\n",
      "    self._final_estimator.fit(Xt, y, **fit_params_last_step)\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py\", line 1345, in fit\n",
      "    check_classification_targets(y)\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/utils/multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  FitFailedWarning)\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/pipeline.py\", line 335, in fit\n",
      "    self._final_estimator.fit(Xt, y, **fit_params_last_step)\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py\", line 1345, in fit\n",
      "    check_classification_targets(y)\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/utils/multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  FitFailedWarning)\n",
      "/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/pipeline.py\", line 335, in fit\n",
      "    self._final_estimator.fit(Xt, y, **fit_params_last_step)\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py\", line 1345, in fit\n",
      "    check_classification_targets(y)\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/utils/multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  FitFailedWarning)\n",
      "/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/pipeline.py\", line 335, in fit\n",
      "    self._final_estimator.fit(Xt, y, **fit_params_last_step)\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py\", line 1345, in fit\n",
      "    check_classification_targets(y)\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/utils/multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  FitFailedWarning)\n",
      "/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/pipeline.py\", line 335, in fit\n",
      "    self._final_estimator.fit(Xt, y, **fit_params_last_step)\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py\", line 1345, in fit\n",
      "    check_classification_targets(y)\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/utils/multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  FitFailedWarning)\n",
      "/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/pipeline.py\", line 335, in fit\n",
      "    self._final_estimator.fit(Xt, y, **fit_params_last_step)\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py\", line 1345, in fit\n",
      "    check_classification_targets(y)\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/utils/multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  FitFailedWarning)\n",
      "/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/pipeline.py\", line 335, in fit\n",
      "    self._final_estimator.fit(Xt, y, **fit_params_last_step)\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py\", line 1345, in fit\n",
      "    check_classification_targets(y)\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/utils/multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  FitFailedWarning)\n",
      "/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/pipeline.py\", line 335, in fit\n",
      "    self._final_estimator.fit(Xt, y, **fit_params_last_step)\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py\", line 1345, in fit\n",
      "    check_classification_targets(y)\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/utils/multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  FitFailedWarning)\n",
      "/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/pipeline.py\", line 335, in fit\n",
      "    self._final_estimator.fit(Xt, y, **fit_params_last_step)\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py\", line 1345, in fit\n",
      "    check_classification_targets(y)\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/utils/multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  FitFailedWarning)\n",
      "/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/pipeline.py\", line 335, in fit\n",
      "    self._final_estimator.fit(Xt, y, **fit_params_last_step)\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py\", line 1345, in fit\n",
      "    check_classification_targets(y)\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/utils/multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  FitFailedWarning)\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/pipeline.py\", line 335, in fit\n",
      "    self._final_estimator.fit(Xt, y, **fit_params_last_step)\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py\", line 1345, in fit\n",
      "    check_classification_targets(y)\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/utils/multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  FitFailedWarning)\n",
      "/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/pipeline.py\", line 335, in fit\n",
      "    self._final_estimator.fit(Xt, y, **fit_params_last_step)\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py\", line 1345, in fit\n",
      "    check_classification_targets(y)\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/utils/multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  FitFailedWarning)\n",
      "/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/pipeline.py\", line 335, in fit\n",
      "    self._final_estimator.fit(Xt, y, **fit_params_last_step)\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py\", line 1345, in fit\n",
      "    check_classification_targets(y)\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/utils/multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  FitFailedWarning)\n",
      "/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/pipeline.py\", line 335, in fit\n",
      "    self._final_estimator.fit(Xt, y, **fit_params_last_step)\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py\", line 1345, in fit\n",
      "    check_classification_targets(y)\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/utils/multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  FitFailedWarning)\n",
      "/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/pipeline.py\", line 335, in fit\n",
      "    self._final_estimator.fit(Xt, y, **fit_params_last_step)\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py\", line 1345, in fit\n",
      "    check_classification_targets(y)\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/utils/multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  FitFailedWarning)\n",
      "/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/pipeline.py\", line 335, in fit\n",
      "    self._final_estimator.fit(Xt, y, **fit_params_last_step)\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py\", line 1345, in fit\n",
      "    check_classification_targets(y)\n",
      "  File \"/Users/joelvenzke/anaconda3/lib/python3.7/site-packages/sklearn/utils/multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  FitFailedWarning)\n"
     ]
    },
    {
     "ename": "ValueError",
     "evalue": "Unknown label type: 'continuous'",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mValueError\u001b[0m                                Traceback (most recent call last)",
      "\u001b[0;32m<ipython-input-8-3da617682165>\u001b[0m in \u001b[0;36m<module>\u001b[0;34m\u001b[0m\n\u001b[1;32m     14\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     15\u001b[0m \u001b[0mgrid_search\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mGridSearchCV\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mclf\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mparam_grid\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mcv\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;36m3\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m---> 16\u001b[0;31m \u001b[0mgrid_search\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mfit\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mX_train\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0my_train\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m     17\u001b[0m \u001b[0mprint\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mgrid_search\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mbest_params_\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py\u001b[0m in \u001b[0;36minner_f\u001b[0;34m(*args, **kwargs)\u001b[0m\n\u001b[1;32m     70\u001b[0m                           FutureWarning)\n\u001b[1;32m     71\u001b[0m         \u001b[0mkwargs\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mupdate\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m{\u001b[0m\u001b[0mk\u001b[0m\u001b[0;34m:\u001b[0m \u001b[0marg\u001b[0m \u001b[0;32mfor\u001b[0m \u001b[0mk\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0marg\u001b[0m \u001b[0;32min\u001b[0m \u001b[0mzip\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0msig\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mparameters\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0margs\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m}\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m---> 72\u001b[0;31m         \u001b[0;32mreturn\u001b[0m \u001b[0mf\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m**\u001b[0m\u001b[0mkwargs\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m     73\u001b[0m     \u001b[0;32mreturn\u001b[0m \u001b[0minner_f\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     74\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_search.py\u001b[0m in \u001b[0;36mfit\u001b[0;34m(self, X, y, groups, **fit_params)\u001b[0m\n\u001b[1;32m    763\u001b[0m             \u001b[0mrefit_start_time\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mtime\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mtime\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    764\u001b[0m             \u001b[0;32mif\u001b[0m \u001b[0my\u001b[0m \u001b[0;32mis\u001b[0m \u001b[0;32mnot\u001b[0m \u001b[0;32mNone\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 765\u001b[0;31m                 \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mbest_estimator_\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mfit\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mX\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0my\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m**\u001b[0m\u001b[0mfit_params\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    766\u001b[0m             \u001b[0;32melse\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    767\u001b[0m                 \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mbest_estimator_\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mfit\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mX\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m**\u001b[0m\u001b[0mfit_params\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/anaconda3/lib/python3.7/site-packages/sklearn/pipeline.py\u001b[0m in \u001b[0;36mfit\u001b[0;34m(self, X, y, **fit_params)\u001b[0m\n\u001b[1;32m    333\u001b[0m             \u001b[0;32mif\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_final_estimator\u001b[0m \u001b[0;34m!=\u001b[0m \u001b[0;34m'passthrough'\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    334\u001b[0m                 \u001b[0mfit_params_last_step\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mfit_params_steps\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0msteps\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0;34m-\u001b[0m\u001b[0;36m1\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0;36m0\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 335\u001b[0;31m                 \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_final_estimator\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mfit\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mXt\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0my\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m**\u001b[0m\u001b[0mfit_params_last_step\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    336\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    337\u001b[0m         \u001b[0;32mreturn\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py\u001b[0m in \u001b[0;36mfit\u001b[0;34m(self, X, y, sample_weight)\u001b[0m\n\u001b[1;32m   1343\u001b[0m                                    \u001b[0morder\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;34m\"C\"\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1344\u001b[0m                                    accept_large_sparse=solver != 'liblinear')\n\u001b[0;32m-> 1345\u001b[0;31m         \u001b[0mcheck_classification_targets\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0my\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m   1346\u001b[0m         \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mclasses_\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mnp\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0munique\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0my\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1347\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/anaconda3/lib/python3.7/site-packages/sklearn/utils/multiclass.py\u001b[0m in \u001b[0;36mcheck_classification_targets\u001b[0;34m(y)\u001b[0m\n\u001b[1;32m    170\u001b[0m     if y_type not in ['binary', 'multiclass', 'multiclass-multioutput',\n\u001b[1;32m    171\u001b[0m                       'multilabel-indicator', 'multilabel-sequences']:\n\u001b[0;32m--> 172\u001b[0;31m         \u001b[0;32mraise\u001b[0m \u001b[0mValueError\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m\"Unknown label type: %r\"\u001b[0m \u001b[0;34m%\u001b[0m \u001b[0my_type\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    173\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    174\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;31mValueError\u001b[0m: Unknown label type: 'continuous'"
     ]
    }
   ],
   "source": [
    "from sklearn.model_selection import GridSearchCV\n",
    "from sklearn.linear_model import LogisticRegression\n",
    "from sklearn.pipeline import Pipeline\n",
    "X, y = make_regression(10000,10,effective_rank=2)\n",
    "X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)\n",
    "clf = Pipeline([\n",
    "    ('kpca', KernelPCA(n_components = 2)),\n",
    "    ('log_reg', LogisticRegression())\n",
    "])\n",
    "param_grid = [{\n",
    "    'kpca__gamma': np.linspace(0.03,0.05,10),\n",
    "    'kpca__kernel': ['rbf', 'sigmoid']\n",
    "}]\n",
    "\n",
    "grid_search = GridSearchCV(clf, param_grid, cv=3)\n",
    "grid_search.fit(X_train, y_train)\n",
    "print(grid_search.best_params_)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "metadata": {},
   "outputs": [],
   "source": [
    "from sklearn.manifold import LocallyLinearEmbedding\n",
    "\n",
    "lle = LocallyLinearEmbedding(n_components=2, n_neighbors=10)\n",
    "X_reduced = lle.fit_transform(X_train)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
